[[builder]]
input_dir = "docs"
output = "html/_docs"

[builder.renderers]
markdown = true

[[builder]]
input_dir = "html"
output = "html/_site"

[[vhost]]
host = "localhost"

[[vhost.files]]
mount = "/docs"
file_dir = "html/_docs"

[[vhost.files]]
file_dir = "html/_site"

[server]
http_bind = ["[::1]:8080", "127.0.0.1:8080"]
