# A virtual host. Virtual hosts and their handlers will be registered in the order they are specified in.
[[vhost]]
host = "localhost" # The Host header that this vhost serves. Must be an exact match.

[[vhost.redir]]
target = "/redir" # The location this redirect targets (ex: /redir would target example.com/redir). Supports wildcards.
dest = "https://example.com" # The URL this redirects to.
permanent = false # If the redirect should be permanent (ex: redirecting from an old domain to a new one), or temporary (ex: link shortening or a "coming soon" page).

[[vhost.files]]
mount = "/test2"
file_dir = "html/test"

[[vhost.files]] # A virtual host file handler.
mount = "/" # The path this file hander serves (ex: /assets would serve files to example.com/assets/...).
file_dir = "html/localhost" # Disk location files are loaded from.



[headers] # HTTP headers added to *all* responses. This will not overwrite existing headers in a response.
server = "KatWebSite"

[server]
# IP addresses to bind the HTTP server to.
http_bind = ["[::1]:8080", "127.0.0.1:8080"]

# The formatting string used for request logs.
log_format = "%{Host}i %a \"%r\" %s %b \"%{Referer}i\" \"%{User-Agent}i\" %D"
# Format (taken from actix_web::middleware::Logger):
# %%		The percent sign
# %a		Peer IP address (or IP address of reverse proxy if used)
# %t		Time when the request started processing (in RFC 3339 format)
# %r		First line of request (Example: GET /test HTTP/1.1)
# %s		Response status code
# %b		Size of response in bytes, including HTTP headers
# %T		Time taken to serve the request, in seconds to 6 decimal places
# %D		Time taken to serve the request, in milliseconds
# %U		Request URL
# %{r}a		"Real IP" remote address (from HTTP headers)
# %{FOO}i	request.headers["FOO"]
# %{FOO}o	response.headers["FOO"]
#%{FOO}e	env_var["FOO"]
