[[vhost]]
host = "localhost"

[[vhost.files]]
file_dir = "/tmp/localhost_test"

[[builder]]
input_dir = "html/localhost_test" # Only files in the root of the mount are parsed, subdirectories are ignored.
output = "/tmp/localhost_test"

[builder.renderers]
data = true
liquid = true
sass = true
markdown = true

[builder.default_dirs] # unimplemented
layout_dir = "_layouts"
include_dir = "_includes"

[builder.default_vars] # unimplemented
title = "Hello World!"

[server]
http_bind = ["[::1]:8080", "127.0.0.1:8080"]
