[[pre_copier]]
input_dir = "../template"
output = "html"
overwrite = true

[[builder]]
input_dir = "html"
output = "html/_site"

[builder.default_vars]
layout = "default.html"
lang = "en"
site_name = "KatWebSite Demo"
generator = "katwebsite"
highlight_js = true

[[vhost]]
host = "localhost"

[[vhost.files]]
file_dir = "html/_site"

[headers]
server = "KatWebSite"

# todo: move the below config out of the example file and into a "best-practices" document

# strict-transport-security = "max-age=63072000;includeSubDomains;preload" # An example of HSTS preloading. Please read more about this from https://hstspreload.org before using it in your own configuration.

#content-security-policy = "default-src 'none'; connect-src 'self'; font-src 'self'; img-src 'self'; media-src 'self'; script-src 'self'; style-src 'self'; base-uri 'none'; plugin-types 'none'; sandbox allow-scripts; frame-ancestors 'none'; block-all-mixed-content; require-trusted-types-for 'script'; upgrade-insecure-requests"
# A strict but reasonable Content-Security-Policy. TODO: Re-evalulate this.
# A reference for CSP values can be found at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy, and https://csp-evaluator.withgoogle.com can be useful for validating your CSP header.

referrer-policy = "no-referrer" # Disables the HTTP referrer header to prevent sensitive data from being logged.
x-content-type-options = "nosniff" # Prevents browsers from sniffing the MIME types of resources. This can be useful when you want to make sure a file is interpreted by it's extension.

[server]
http_bind = ["[::1]:8080", "127.0.0.1:8080"]
