# This config file allows you to view a compiled version of KatWebSite's docs through your web browser.

[[builder]]
input_dir = "."
output = "/tmp/docs"

[builder.renderers]
markdown = true
layout = true

[builder.default_dirs]
layout_dir = "../template/_layouts"

[builder.default_vars]
layout = "default.html"

[[vhost]]
host = "localhost"

[[vhost.files]]
file_dir = "/tmp/docs"

[server]
http_bind = ["[::1]:8080", "127.0.0.1:8080"]
